class CreateTimetables < ActiveRecord::Migration[6.1]
  def change
    create_table :timetables do |t|
      t.string :title11
      t.string :title12
      t.string :title13
      t.string :title14
      t.string :title15
      t.string :title16
      t.string :title21
      t.string :title22
      t.string :title23
      t.string :title24
      t.string :title25
      t.string :title26
      t.string :title31
      t.string :title32
      t.string :title33
      t.string :title34
      t.string :title35
      t.string :title36
      t.string :title41
      t.string :title42
      t.string :title43
      t.string :title44
      t.string :title45
      t.string :title46
      t.string :title51
      t.string :title52
      t.string :title53
      t.string :title54
      t.string :title55
      t.string :title56
      t.string :title61
      t.string :title62
      t.string :title63
      t.string :title64
      t.string :title65
      t.string :title66
      t.time :start_time1
      t.time :start_time2
      t.time :start_time3
      t.time :start_time4
      t.time :start_time5
      t.time :start_time6
      t.time :finish_time1
      t.time :finish_time2
      t.time :finish_time3
      t.time :finish_time4
      t.time :finish_time5
      t.time :finish_time6
      t.string :classroom11
      t.string :classroom12
      t.string :classroom13
      t.string :classroom14
      t.string :classroom15
      t.string :classroom16
      t.string :classroom21
      t.string :classroom22
      t.string :classroom23
      t.string :classroom24
      t.string :classroom25
      t.string :classroom26
      t.string :classroom31
      t.string :classroom32
      t.string :classroom33
      t.string :classroom34
      t.string :classroom35
      t.string :classroom36
      t.string :classroom41
      t.string :classroom42
      t.string :classroom43
      t.string :classroom44
      t.string :classroom45
      t.string :classroom46
      t.string :classroom51
      t.string :classroom52
      t.string :classroom53
      t.string :classroom54
      t.string :classroom55
      t.string :classroom56
      t.string :classroom61
      t.string :classroom62
      t.string :classroom63
      t.string :classroom64
      t.string :classroom65
      t.string :classroom66
      t.integer :user_id

      t.timestamps
    end
  end
end
